# Generated by Django 4.0 on 2021-12-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('discription', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='img', verbose_name='Foto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Prices')),
            ],
        ),
    ]
